import 'models.dart';

const washingSource =
    'https://www.fsis.usda.gov/food-safety/safe-food-handling-and-preparation/food-safety-basics/washing-food-does-it-promote-food';
const fireSource =
    'https://www.usfa.fema.gov/prevention/home-fires/prevent-fires/cooking/';
const temperatureSource =
    'https://www.fsis.usda.gov/food-safety/safe-food-handling-and-preparation/food-safety-basics/safe-temperature-chart';
const braiseSource =
    'https://iastate.pressbooks.pub/fshn115/chapter/11-1-moist-heat-methods-introduction/';

const knowledgeCards = <Knowledge>[
  Knowledge(
    'beef-choice',
    '牛腩怎么选？',
    '食材挑选',
    '选适合久炖的部位，带一点筋和脂肪。',
    '牛腩和牛肋条适合湿热慢炖。脂肪带来香气，结缔组织需要足够时间变软。优先选正规冷链销售、在保质期内的肉；颜色不能单独判断安全。',
    '牛腱：筋更多，切块和炖煮时间需要调整。里脊：更适合快炒，长时间炖容易失去嫩口感。',
    sourceName: 'Iowa State University · 湿热烹饪原理；选材为家庭实践',
    sourceUrl: braiseSource,
  ),
  Knowledge(
    'beef-size',
    '为什么切成 3～4 厘米？',
    '预处理',
    '留一点体积，久炖后仍有口感。',
    '牛腩炖煮后会缩小。大小均匀能让同一锅肉更接近同时变软；3～4 厘米是这份家庭做法的建议，不是固定标准。',
    '切小块：通常更快变软，但容易碎。切大块：形状完整，需要更长时间，以实际软烂程度为准。',
  ),
  Knowledge(
    'wash-meat',
    '生牛肉需要冲洗吗？',
    '食材安全',
    '不建议冲洗生肉，避免水花传播污染。',
    '流水冲洗不能可靠去除病菌，反而可能把生肉汁液溅到水槽和食物上。正规购买的牛肉可用厨房纸吸去表面汁液；生熟砧板分开，处理后洗手并清洁接触面。充分加热才是关键。',
    '浸泡不是食品安全步骤。如果因风味选择浸泡，应放冰箱内进行，倒掉浸泡液，清洁容器；本菜谱省略浸泡。',
    sourceName: 'USDA FSIS · 食物清洗与交叉污染',
    sourceUrl: washingSource,
  ),
  Knowledge(
    'blanch',
    '焯水和直接煎，有什么不同？',
    '方法比较',
    '焯水偏清爽，煎香偏浓郁。',
    '本做法用冷水加热焯牛腩，水沸后撇沫、短煮再捞出，便于减少汤里的浮沫。焯水时间从沸腾后开始算，不能把这一步当作已经彻底煮熟。',
    '直接煎：吸干表面水分再分批煎，增加焦香和浓郁感。焯水：汤更清爽，但少一些煎香。两种方法都需要后续充分炖熟。',
  ),
  Knowledge(
    'foam',
    '锅里的浮沫是什么？',
    '烹饪原理',
    '主要是受热凝结的蛋白质等成分。',
    '肉汁中的蛋白质受热后凝结，和脂肪、碎屑形成浮沫。撇去它主要是为了汤的外观和口感；浮沫多少不代表肉是否安全。',
    '想要清汤：及时撇沫。浓味炖菜：焯水后捞出即可，不必追求完全无沫。',
  ),
  Knowledge(
    'tomato-choice',
    '什么番茄适合炖牛腩？',
    '食材挑选',
    '成熟、有香气的番茄更容易炒出汁。',
    '选择表皮完整、成熟但没有霉斑的番茄。品种、成熟度会影响酸甜和水分；先尝熟番茄汁，再少量调整糖和盐。洗番茄应使用清水。',
    '普通成熟番茄：汁水多、酸甜自然。小番茄：风味可能更集中，可切半使用。罐装番茄：更稳定，注意产品是否已经加盐。',
  ),
  Knowledge(
    'tomato-two',
    '为什么番茄分两次放？',
    '烹饪原理',
    '一半做汤底，一半保留形状。',
    '先炒的一半会逐渐软化、释放汁水，形成浓汤底；后放的一半保留更明显的番茄口感。',
    '一次全放：汤底更均匀，番茄基本融化。全部后放：块状更明显，汤汁通常较淡。',
  ),
  Knowledge(
    'braise',
    '小火慢炖，怎样才算刚好？',
    '火候判断',
    '保持轻微冒泡，肉能轻松穿透。',
    '轻微冒泡的湿热环境适合把牛腩炖软。锅具、肉块大小和部位都会影响时间；80 分钟只是首次检查时间，可能需要再炖 20～40 分钟或更久。用筷子能较容易插入、咀嚼软嫩来判断口感。',
    '普通锅：方便观察水量。压力锅：时间通常更短，应另按设备说明和压力锅专用菜谱操作，不能直接沿用这里的计时。',
    sourceName: 'Iowa State University · 湿热烹饪原理；时间为家庭估计',
    sourceUrl: braiseSource,
  ),
  Knowledge(
    'watch-pot',
    '炖煮时可以离开吗？',
    '厨房安全',
    '留在家中，定期回到灶边看锅。',
    '炒制和大火收汁时留在灶边。小火炖煮仍需定期检查汤量和火焰；本应用每 10 分钟提醒一次，但不能替代照看。发现汤量不足应调整火力并适量补热水。离家、睡觉或无人照看前关火。',
    '需要暂时离开：先关火。电器也要遵循说明书。手机静音、省电或被强制停止可能影响提醒。',
    sourceName: 'USFA · 厨房火灾预防',
    sourceUrl: fireSource,
  ),
  Knowledge(
    'doneness',
    '时间到了，就一定熟了吗？',
    '食材安全',
    '计时帮助安排，不能证明食物安全。',
    '安全熟度应用食物温度计判断。USDA 建议整块牛肉中心至少 63°C 并静置 3 分钟；禽肉至少 74°C，剩菜再次加热至少 74°C。牛腩软烂是口感指标，需要比最低安全温度更长的湿热烹饪。',
    '温度计：判断安全加热。筷子穿透和咀嚼口感：判断软烂。肉的颜色或一个固定分钟数不能单独证明安全。',
    sourceName: 'USDA FSIS · 安全中心温度',
    sourceUrl: temperatureSource,
  ),
  Knowledge(
    'reduce',
    '收汁要收到什么程度？',
    '火候判断',
    '汤汁稍浓、能附着食材就可以。',
    '打开锅盖让水分蒸发，间歇翻动锅底。汤汁越少越容易糊，需要留在灶边观察。关火后余热也会使汤变稠，可以留一点汁配饭。',
    '喜欢汤多：省略或缩短收汁。喜欢浓稠：多收一会儿，先少盐，最后尝味调整。',
  ),
  Knowledge(
    'lotus',
    '莲藕为什么要最后再尝软硬？',
    '食材挑选',
    '品种和切块大小都会影响口感。',
    '莲藕有偏粉和偏脆的口感差异，外观不能保证某种口感。汤藕可选商家标注适合炖汤的品种，切均匀块，以筷子能穿透和尝味判断。',
    '喜欢粉糯：延长小火炖煮。喜欢脆：缩短莲藕炖煮时间，但排骨仍要充分煮熟。',
  ),
  Knowledge(
    'steam',
    '蒸菜从什么时候开始计时？',
    '基础技法',
    '水沸、蒸汽稳定后再计时。',
    '蒸锅先把水烧沸，放入食物后盖好锅盖。蒸汽恢复稳定再开始计时；蒸锅大小、厚度和份量都会改变实际用时。保持水量充足，揭盖时让蒸汽朝远离身体的方向散开。',
    '冷水开始蒸：总时间会变化，需要专门适配。这里统一采用水沸后上锅的做法。',
  ),
  Knowledge(
    'egg',
    '蒸蛋怎么更细腻？',
    '方法比较',
    '温水、过滤、温和蒸汽，减少气泡。',
    '蛋液加约 1.5 倍体积温水，轻轻搅匀并过滤。用耐热盘盖住碗口，防止冷凝水滴入。蒸好应整体凝固，中心没有流动蛋液；蛋类中心安全温度参考 71°C。',
    '水少：更结实。水多：更嫩但难凝固。大火：容易出现孔洞，小火稳定蒸汽更好控制。',
    sourceName: 'USDA FSIS · 安全中心温度；配比为家庭做法',
    sourceUrl: temperatureSource,
  ),
  Knowledge(
    'greens',
    '青菜怎么炒更有口感？',
    '基础技法',
    '沥干水，菜梗先下，菜叶后下。',
    '清水洗净后充分沥干，菜梗和菜叶分开。菜梗较厚需要多炒一会儿，再放菜叶，最后尝味。不要把锅塞得太满，以免炒成一锅水。',
    '快炒：口感较脆。先焯后炒：易于控制份量，但会多一个步骤。烹饪时始终留在灶边。',
  ),
  Knowledge(
    'pumpkin',
    '南瓜切多大更好蒸？',
    '预处理',
    '厚度均匀，比固定时间更重要。',
    '清洗南瓜，用稳固砧板切约 2 厘米厚的块，去籽。硬皮品种可以去皮，切时手指避开刀刃。以筷子能轻松穿透为口感判断。',
    '薄片：更快软，容易散。厚块：保持形状，但需要延长蒸制。',
  ),
  Knowledge(
    'chestnut',
    '栗子什么时候放？',
    '食材处理',
    '本做法用已经去壳去内皮的栗仁。',
    '栗仁和鸡肉一同炖煮，最后试一颗，确保内部软糯。冷冻栗仁按包装说明处理；生栗子的去壳有额外步骤和用时，不计入这份菜谱。',
    '熟栗仁：末段再加入，避免炖碎。生栗仁：早点加入，时间随大小调整。',
  ),
  Knowledge(
    'chicken',
    '鸡肉怎样判断安全熟度？',
    '食材安全',
    '最厚处中心达到至少 74°C。',
    '用食物温度计插入鸡肉最厚处，避开骨头，中心温度至少达到 74°C。仅凭没有血色或煮了多少分钟并不可靠。处理生鸡后洗手，清洁刀和砧板。',
    '带骨鸡块：测温要避开骨头。去骨鸡腿肉：更易均匀熟透，本做法优先使用去骨肉。',
    sourceName: 'USDA FSIS · 安全中心温度',
    sourceUrl: temperatureSource,
  ),
];

const recipes = <Recipe>[
  Recipe(
    id: 'tomato-beef',
    name: '番茄牛腩',
    subtitle: '把秋天炖进一锅里',
    art: 'stew',
    color: 0xFFFFE0CF,
    description: '番茄的酸甜慢慢融进牛腩，留一勺浓汤拌饭。从挑肉到控制火候，每一步都有解释。',
    activeMinutes: 35,
    waitMinutes: 80,
    servings: 2,
    tags: ['家常菜', '炖', '牛肉', '下饭菜', '进阶'],
    months: [1, 2, 3, 9, 10, 11, 12],
    tools: ['炒锅 / 厚底炖锅', '菜刀与生熟分开砧板', '量勺', '食物温度计'],
    ingredients: [
      Ingredient('牛腩', 500, '克'),
      Ingredient('番茄', 600, '克'),
      Ingredient('洋葱', 100, '克'),
      Ingredient('姜', 10, '克'),
      Ingredient('食用油', 15, '毫升'),
      Ingredient('生抽', 15, '毫升'),
      Ingredient('盐', 2, '克（最后尝味调整）'),
      Ingredient('热水', 800, '毫升（以没过食材为准）'),
    ],
    steps: [
      CookStep(
        '切牛腩，准备配菜',
        '牛腩切成 3～4 厘米均匀块。番茄清水洗净切块，分成两份；洋葱切块，姜切片。',
        '先处理蔬菜，再用生肉专用砧板切肉。',
        'cut',
        safety: '不冲洗生肉；处理后洗手，清洁刀和砧板。',
        knowledge: ['beef-choice', 'beef-size', 'wash-meat'],
      ),
      CookStep(
        '牛腩冷水下锅焯水',
        '牛腩放进锅，加冷水没过肉。加热至沸腾，撇去浮沫，再煮约 3 分钟后捞出沥干。',
        '计时从水沸开始。焯水后仍要继续炖熟。',
        'pot',
        minutes: 3,
        safety: '留在灶边；捞肉时小心沸水和蒸汽。',
        knowledge: ['blanch', 'foam'],
      ),
      CookStep(
        '炒出番茄汤底',
        '锅中加油，中火炒香姜片和洋葱约 2 分钟。加入一半番茄，翻炒约 5 分钟至软化出汁。',
        '番茄边缘软塌，锅底出现红色汁水。',
        'tomato',
        minutes: 5,
        safety: '食材沥干后下锅，防止热油飞溅；炒制时留在灶边。',
        knowledge: ['tomato-choice', 'tomato-two'],
      ),
      CookStep(
        '加牛腩和热水',
        '加入牛腩和生抽，翻匀。倒入热水，水量以刚没过食材为准。烧沸后转小火，盖上锅盖。',
        '维持轻微冒泡，避免持续猛烈翻滚。',
        'pot',
        safety: '热水沿锅边缓慢加入，手避开蒸汽。',
        knowledge: ['braise'],
      ),
      CookStep(
        '小火慢炖，定期看锅',
        '先炖约 80 分钟，每 10 分钟检查火力和水量。汤少时适量补热水；计时结束后检查牛腩是否软烂。',
        '筷子较容易穿透。如果仍硬，再炖 20～40 分钟或更久，按实际口感调整。',
        'stew',
        minutes: 80,
        watchPot: true,
        safety: '留在家中，定期回灶边。离开或睡觉前必须关火。提醒不能替代照看。',
        knowledge: ['braise', 'watch-pot', 'doneness'],
      ),
      CookStep(
        '放入剩余番茄',
        '牛腩软烂后加入另一半番茄，小火再煮约 10 分钟。最后少量加盐，尝味再调整。',
        '番茄变软，但还有块状口感。',
        'tomato',
        minutes: 10,
        watchPot: true,
        safety: '留意汤量，避免干锅。用干净的勺子尝熟汤。',
        knowledge: ['tomato-two', 'watch-pot'],
      ),
      CookStep(
        '收汁，关火出锅',
        '开盖，稍调大火并翻动约 3～5 分钟。汤汁稍浓即可关火。用食物温度计确认安全熟度，再盛入碗中。',
        '汤汁能附着牛肉；想拌饭可以多留一点汁。',
        'stew',
        minutes: 3,
        safety: '收汁时守在灶边。完成后确认炉火已关，锅柄朝内。',
        knowledge: ['reduce', 'doneness'],
      ),
    ],
  ),
  Recipe(
    id: 'lotus-soup',
    name: '莲藕排骨汤',
    subtitle: '一碗暖乎乎的秋日汤',
    art: 'soup',
    color: 0xFFE7E7D2,
    description: '清爽排骨汤搭配粉糯莲藕。用小火和耐心，把家常食材炖出温暖。',
    activeMinutes: 20,
    waitMinutes: 80,
    tags: ['家常菜', '炖', '猪肉', '汤羹', '简单'],
    months: [9, 10, 11, 12, 1, 2],
    tools: ['汤锅', '生熟分开砧板', '汤勺', '食物温度计'],
    ingredients: [
      Ingredient('排骨', 500, '克'),
      Ingredient('莲藕', 400, '克'),
      Ingredient('姜', 10, '克'),
      Ingredient('盐', 2, '克（尝味调整）'),
      Ingredient('水', 1200, '毫升（保持没过食材）'),
    ],
    steps: [
      CookStep(
        '准备排骨和莲藕',
        '莲藕清水洗净去皮，切均匀滚刀块。排骨使用已切段产品，吸干表面汁液。姜切片。',
        '生熟工具分开。',
        'cut',
        safety: '不冲洗生肉，处理后洗手。',
        knowledge: ['lotus', 'wash-meat'],
      ),
      CookStep(
        '排骨焯水',
        '排骨加冷水没过。烧沸后撇沫，继续煮约 3 分钟，捞出沥干。',
        '从沸腾后计时。',
        'pot',
        minutes: 3,
        safety: '小心沸水，留在灶边。',
        knowledge: ['blanch', 'foam'],
      ),
      CookStep(
        '小火炖排骨',
        '排骨、姜和水入锅，烧沸后小火炖 40 分钟。每 10 分钟查看水量。',
        '轻微冒泡，水量覆盖食材。',
        'soup',
        minutes: 40,
        watchPot: true,
        safety: '留在家中，定期看锅；缺水补热水。',
        knowledge: ['watch-pot', 'braise'],
      ),
      CookStep(
        '加入莲藕',
        '加入莲藕，再小火炖约 40 分钟。确认排骨和莲藕已软，用温度计判断肉的安全熟度。',
        '若莲藕仍硬，可延长炖煮。',
        'soup',
        minutes: 40,
        watchPot: true,
        safety: '计时不代表安全熟度。',
        knowledge: ['lotus', 'doneness'],
      ),
      CookStep(
        '尝味，关火',
        '少量加盐，尝味后调整。关火再盛汤。',
        '排骨软嫩，莲藕达到喜欢的口感。',
        'soup',
        safety: '确认关火，盛汤时防烫。',
        knowledge: ['doneness'],
      ),
    ],
  ),
  Recipe(
    id: 'steamed-egg',
    name: '嫩滑蒸蛋',
    subtitle: '第一次做饭，也能很温柔',
    art: 'egg',
    color: 0xFFFFECC5,
    description: '两颗鸡蛋，一碗嫩滑。学会比例和蒸汽控制，把基础菜做好。',
    activeMinutes: 8,
    waitMinutes: 12,
    tags: ['家常菜', '蒸', '鸡蛋', '快手菜', '第一次做饭'],
    months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    tools: ['蒸锅', '耐热碗和盘', '滤网', '食物温度计'],
    ingredients: [
      Ingredient('鸡蛋', 2, '个'),
      Ingredient('温水', 150, '毫升（约蛋液体积 1.5 倍）'),
      Ingredient('盐', 1, '克'),
      Ingredient('生抽', 5, '毫升'),
      Ingredient('香油', 2, '毫升'),
    ],
    steps: [
      CookStep(
        '打散鸡蛋',
        '鸡蛋打散，加盐和约蛋液体积 1.5 倍的温水，轻轻搅匀。',
        '温水不烫手，避免烫熟蛋液。',
        'egg',
        knowledge: ['egg'],
      ),
      CookStep(
        '过滤蛋液',
        '蛋液过筛入耐热碗，撇去气泡。用耐热盘盖住碗口。',
        '蒸锅加足量水，先烧沸。',
        'egg',
        knowledge: ['egg', 'steam'],
      ),
      CookStep(
        '小火蒸蛋',
        '水沸后上锅，蒸汽恢复后，小火蒸约 12 分钟。',
        '蛋液整体凝固，中心无流动液体；中心至少 71°C。',
        'egg',
        minutes: 12,
        safety: '留在厨房，防止蒸锅烧干；开盖先让蒸汽远离身体。',
        knowledge: ['steam', 'egg'],
      ),
      CookStep(
        '调味，关火出锅',
        '确认熟透后关火，戴隔热手套取碗。淋少量生抽和香油。',
        '热碗放隔热垫上。',
        'egg',
        safety: '蒸碗和蒸汽很烫，勿徒手触碰。',
        knowledge: ['doneness'],
      ),
    ],
  ),
  Recipe(
    id: 'greens',
    name: '蒜蓉小青菜',
    subtitle: '一抹清绿，刚刚好',
    art: 'greens',
    color: 0xFFDAEDCF,
    description: '菜梗先下，菜叶后下。一道清爽快手菜，练习掌握翻炒和调味。',
    activeMinutes: 12,
    waitMinutes: 0,
    tags: ['家常菜', '炒', '蔬菜', '快手菜', '第一次做饭'],
    months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    tools: ['炒锅', '砧板', '锅铲'],
    ingredients: [
      Ingredient('小青菜', 300, '克'),
      Ingredient('蒜', 10, '克'),
      Ingredient('食用油', 10, '毫升'),
      Ingredient('盐', 1.5, '克（尝味调整）'),
    ],
    steps: [
      CookStep(
        '洗菜，沥干',
        '青菜去掉坏叶，掰开用清水洗净，充分沥干。菜梗和菜叶分开，蒜切末。',
        '避免大量水带进油锅。',
        'greens',
        knowledge: ['greens'],
      ),
      CookStep(
        '炒香蒜末和菜梗',
        '锅中加油，中火炒蒜末约 20 秒，再放菜梗炒约 1 分钟。',
        '蒜香出来即可，别炒焦。',
        'greens',
        safety: '湿食材不要直接扔入热油，留在灶边。',
        knowledge: ['greens'],
      ),
      CookStep(
        '加入菜叶',
        '加入菜叶继续翻炒约 2 分钟，直到菜叶软、菜梗达到喜欢的口感。最后少量加盐。',
        '锅太满时分批炒。',
        'greens',
        minutes: 2,
        safety: '全程照看，勿把手靠近热油。',
        knowledge: ['greens'],
      ),
      CookStep(
        '关火，盛盘',
        '尝味，关火盛盘，及时食用。',
        '菜叶舒展柔软，菜梗保持一点脆感。',
        'greens',
        safety: '确认关火。',
        knowledge: ['greens'],
      ),
    ],
  ),
  Recipe(
    id: 'pumpkin',
    name: '清蒸南瓜',
    subtitle: '把南瓜的甜留住',
    art: 'pumpkin',
    color: 0xFFFFDFC1,
    description: '只需要南瓜和蒸汽。少一点调味，尝到食材本来的香甜。',
    activeMinutes: 8,
    waitMinutes: 20,
    tags: ['家常菜', '蒸', '蔬菜', '简单', '一人食'],
    months: [8, 9, 10, 11, 12],
    tools: ['蒸锅', '耐热盘', '砧板', '隔热手套'],
    ingredients: [Ingredient('南瓜', 500, '克')],
    steps: [
      CookStep(
        '南瓜洗净切块',
        '洗净南瓜，去籽，切成约 2 厘米厚的均匀块，硬皮可以去掉。',
        '砧板放稳，手指避开刀刃。',
        'pumpkin',
        safety: '南瓜较硬，切时小心滑刀。',
        knowledge: ['pumpkin'],
      ),
      CookStep(
        '摆盘，烧水',
        '南瓜平铺耐热盘，蒸锅加足量水并烧沸。',
        '不要叠得过厚。',
        'pumpkin',
        knowledge: ['steam'],
      ),
      CookStep(
        '蒸至软糯',
        '水沸后上锅，蒸汽恢复后蒸约 20 分钟。筷子能轻松穿透即可，不够软继续蒸。',
        '计时是估计，厚度影响用时。',
        'pumpkin',
        minutes: 20,
        safety: '留在厨房，检查蒸锅水量，避免烧干。',
        knowledge: ['pumpkin', 'steam'],
      ),
      CookStep(
        '关火，取盘',
        '确认关火，揭盖让蒸汽朝外散开，戴隔热手套取盘。',
        '稍放凉再吃。',
        'pumpkin',
        safety: '盘底和蒸汽很烫。',
        knowledge: ['steam'],
      ),
    ],
  ),
  Recipe(
    id: 'chestnut-chicken',
    name: '栗子焖鸡',
    subtitle: '栗香遇上软嫩鸡腿',
    art: 'chicken',
    color: 0xFFE8DCCC,
    description: '栗仁粉糯，鸡腿鲜香。秋日家常焖菜，使用去骨鸡腿肉和去皮栗仁。',
    activeMinutes: 20,
    waitMinutes: 30,
    tags: ['家常菜', '炖', '鸡肉', '下饭菜', '简单'],
    months: [9, 10, 11, 12],
    tools: ['厚底锅', '生熟分开砧板', '食物温度计'],
    ingredients: [
      Ingredient('去骨鸡腿肉', 400, '克'),
      Ingredient('去皮生栗仁', 150, '克'),
      Ingredient('姜', 10, '克'),
      Ingredient('生抽', 15, '毫升'),
      Ingredient('食用油', 10, '毫升'),
      Ingredient('热水', 400, '毫升（基本覆盖食材）'),
    ],
    steps: [
      CookStep(
        '切鸡腿肉',
        '鸡肉吸干表面汁液，切约 3 厘米块。姜切片，准备好去壳去内皮栗仁。',
        '生肉和其他食材使用不同工具。',
        'cut',
        safety: '不要冲洗生鸡；处理后洗手和清洁工具。',
        knowledge: ['wash-meat', 'chestnut'],
      ),
      CookStep(
        '煎香鸡肉',
        '锅中加油，中火炒香姜。加入鸡肉分批煎炒约 5 分钟，表面稍有焦香。',
        '只煎表面，还要继续焖熟。',
        'chicken',
        minutes: 5,
        safety: '肉表面沥干，防热油飞溅，留在灶边。',
        knowledge: ['chicken'],
      ),
      CookStep(
        '栗仁一起焖',
        '加入栗仁、生抽和热水，烧沸后盖盖转小火焖约 30 分钟，每 10 分钟看锅。',
        '栗仁软糯，水量不够补热水。',
        'chicken',
        minutes: 30,
        watchPot: true,
        safety: '留在家中，定期看锅。',
        knowledge: ['chestnut', 'watch-pot'],
      ),
      CookStep(
        '测温，收汁关火',
        '测鸡肉最厚处至少 74°C；不够就继续加热。栗仁软后，开盖略收汁，关火盛盘。',
        '肉熟、栗仁软、汤汁稍浓。',
        'chicken',
        safety: '收汁守在灶边，完成确认关火。',
        knowledge: ['chicken', 'reduce'],
      ),
    ],
  ),
];

const monthlyIngredients = <int, List<String>>{
  1: ['白萝卜', '白菜', '冬笋', '山药'],
  2: ['春笋', '菠菜', '韭菜', '萝卜'],
  3: ['春笋', '荠菜', '豌豆', '菠菜'],
  4: ['芦笋', '豌豆', '蚕豆', '春笋'],
  5: ['黄瓜', '蚕豆', '西葫芦', '生菜'],
  6: ['番茄', '黄瓜', '茄子', '丝瓜'],
  7: ['冬瓜', '丝瓜', '苦瓜', '茄子'],
  8: ['南瓜', '玉米', '毛豆', '番茄'],
  9: ['莲藕', '南瓜', '栗子', '山药'],
  10: ['栗子', '莲藕', '南瓜', '山药'],
  11: ['白菜', '白萝卜', '莲藕', '山药'],
  12: ['冬笋', '白菜', '白萝卜', '菠菜'],
};

List<Recipe> seasonalRecipes(int month) =>
    recipes.where((r) => r.months.contains(month)).toList();
String seasonName(int month) => month >= 3 && month <= 5
    ? '春'
    : month >= 6 && month <= 8
    ? '夏'
    : month >= 9 && month <= 11
    ? '秋'
    : '冬';
